<a href="https://colab.research.google.com/github/MuizSarwar/Deep-Learning-study-materials-/blob/main/nn_module(class_04).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import torch.nn as nn

In [15]:
!pip install torchinfo

In [4]:
#dataset
features = torch.rand(10,5)   #dataset will have 5 features & 10 values in each.
features

tensor([[0.4309, 0.3117, 0.2391, 0.5512, 0.2210],
        [0.0274, 0.5457, 0.2718, 0.0330, 0.2026],
        [0.6319, 0.2376, 0.8844, 0.6277, 0.2225],
        [0.3398, 0.5413, 0.6685, 0.6305, 0.2568],
        [0.4444, 0.7170, 0.3406, 0.7067, 0.9366],
        [0.3066, 0.2211, 0.0506, 0.4224, 0.4423],
        [0.3703, 0.5795, 0.6060, 0.5111, 0.8886],
        [0.4448, 0.7813, 0.0492, 0.2345, 0.3508],
        [0.4632, 0.5920, 0.4653, 0.0455, 0.6069],
        [0.8217, 0.3525, 0.1680, 0.0138, 0.7246]])

#Version - 01 ( Single Layer )

In [6]:
#----> A NN module with n inputes and 1 output <-----
class ModelVersion01(nn.Module):
  def __init__(self,feature_num):
    super().__init__()
    self.linear = nn.Linear(feature_num,1)
    self.sigmoid = nn.Sigmoid()


  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [19]:
#create model
model_v1 = ModelVersion01(features.shape[1])

#forward pass
model_v1(features)

tensor([[0.4386],
        [0.5186],
        [0.4325],
        [0.4643],
        [0.4979],
        [0.4678],
        [0.5188],
        [0.4776],
        [0.5164],
        [0.4780]], grad_fn=<SigmoidBackward0>)

In [14]:
#weights and bias of the model:-
model_weights = model_v1.linear.weight
model_bias = model_v1.linear.bias

print("Model weights:------------")
display(model_weights)
print("Model bias:---------------")
display(model_bias)

Model weights:------------


Parameter containing:
tensor([[-0.0883,  0.1529,  0.2897, -0.0989, -0.1374]], requires_grad=True)

Model bias:---------------


Parameter containing:
tensor([-0.2785], requires_grad=True)

In [16]:
from torchinfo import summary
summary(model_v1,input_size=features.shape)

Layer (type:depth-idx)                   Output Shape              Param #
ModelVersion01                           [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

#Version - 02 ( Multiple Layer )


In [18]:
#-------------> layer:01 ----> input:feature_num  & output:3
#-------------> layer:02 ----> input:3 & output:1

class ModelVersion02(nn.Module):
  def __init__(self,feature_num):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(feature_num,3), #index=0
        nn.ReLU(),  #index=1
        nn.Linear(3,1), #index=2
        nn.Sigmoid()  #index = 3
    )


  def forward(self,features):
    out = self.network(features)
    return out

In [20]:
from torch.return_types import mode
#create model
model_v2 = ModelVersion02(features.shape[1])

#forward pass
model_v2(features)

tensor([[0.5162],
        [0.5196],
        [0.5003],
        [0.5144],
        [0.5350],
        [0.5214],
        [0.5233],
        [0.5204],
        [0.5117],
        [0.5028]], grad_fn=<SigmoidBackward0>)

In [24]:
#Weights and bias
layer01_weights = model_v2.network[0].weight
layer01_bias = model_v2.network[0].bias

layer02_weights = model_v2.network[2].weight
layer02_bias = model_v2.network[2].bias

In [25]:
summary(model_v2,input_size=features.shape)

Layer (type:depth-idx)                   Output Shape              Param #
ModelVersion02                           [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00