<a href="https://colab.research.google.com/github/MuizSarwar/Deep-Learning-study-materials-/blob/main/pytorch_class_01(forward_and_backward_propagation).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch

In [5]:
data = torch.tensor(
    [
       #X1-X2-y
        [2,3,3],
        [5,6,4],
        [7,8,5]
    ]
)


X = data[:,0:2].float()
y = data[:,2].float()

display(X)
display(y)

tensor([[2., 3.],
        [5., 6.],
        [7., 8.]])

tensor([3., 4., 5.])

In [6]:
#---------------Weight initialization-----------------
def initialize_parameters(layer_dimension):
  torch.manual_seed(3)
  parameters = {}
  L = len(layer_dimension)

  for l in range(1,L):
    parameters['W'+str(l)] = torch.ones((layer_dimension[l-1],layer_dimension[l]))*0.1
    parameters['b'+str(l)] = torch.zeros((layer_dimension[l],1))

  return parameters

In [7]:
param = initialize_parameters([2,2,1])

####Forward Propagation

In [8]:
#Perceptron output ( y = W.t * A + b  )
def perceptron_output(input_param,weight,bias):
  return torch.matmul(weight.T,input_param)+bias

In [9]:
#Forward Propagation:
def forward_propagation(X,parameters):
  A = X
  L = len(parameters)//2

  for l in range(1,L+1):
    w = parameters['W'+str(l)]
    b = parameters['b'+str(l)]
    A = perceptron_output(w,A,b)

  #final output will store at A
  return X,A  #returning input and final output

In [10]:
for x in X:
  input_data,y_hat = forward_propagation(x.reshape(2,1),param)
  print("Input data:")
  display(x.reshape(2,1))
  print("Output:")
  display(y_hat)
  print('----------------------------------------------------')

Input data:


tensor([[2.],
        [3.]])

Output:


tensor([[0.1000],
        [0.1000]])

----------------------------------------------------
Input data:


tensor([[5.],
        [6.]])

Output:


tensor([[0.2200],
        [0.2200]])

----------------------------------------------------
Input data:


tensor([[7.],
        [8.]])

Output:


tensor([[0.3000],
        [0.3000]])

----------------------------------------------------


####Backward Propagation

In [11]:
#------------------((( Need to learn again )))--------------------------
def update_parameters(parameters, y, y_hat, A1, X, lr=0.001):

    err_signal = 2 * (y - y_hat)

     #  Save OLD W2 values before updating
    W2_00_old = parameters['W2'][0, 0].item()
    W2_10_old = parameters['W2'][1, 0].item()

    # Update Layer 2




    parameters['W2'][0, 0] += lr * err_signal * A1[0, 0]
    parameters['W2'][1, 0] += lr * err_signal * A1[1, 0]
    parameters['b2'][0, 0] += lr * err_signal #


    parameters['W1'][0, 0] += lr * err_signal * parameters['W2'][0, 0] * X[0, 0]
    parameters['W1'][0, 1] += lr * err_signal * parameters['W2'][0, 0] * X[1, 0]
    parameters['b1'][0, 0] += lr * err_signal * parameters['W2'][0, 0]

    parameters['W1'][1, 0] += lr * err_signal * parameters['W2'][1, 0] * X[0, 0]
    parameters['W1'][1, 1] += lr * err_signal * parameters['W2'][1, 0] * X[1, 0]
    parameters['b1'][1, 0] += lr * err_signal * parameters['W2'][1, 0]

    return parameters

In [13]:
#----------------------(((Need to learn again )))--------------



params = initialize_parameters([2, 2, 1])
epochs = 5

for i in range(epochs):
    epoch_loss = 0
    for j in range(X.shape[0]):
        # Prepare sample
        X_sample = X[j].reshape(2, 1)
        y_sample = y[j]

        # Forward
        y_hat, A1 = forward_propagation(X_sample, params)
        y_hat_scalar = y_hat[0, 0]

        # Update
        params = update_parameters(params, y_sample, y_hat_scalar, A1, X_sample)

        # Loss calculation
        loss = (y_sample - y_hat_scalar) ** 2
        epoch_loss += loss.item()

    print(f"Epoch - {i+1} Loss - {epoch_loss / X.shape[0]}")

Epoch - 1 Loss - 2.0
Epoch - 2 Loss - 2.0
Epoch - 3 Loss - 2.0
Epoch - 4 Loss - 2.0
Epoch - 5 Loss - 2.0
